# Generated by Django 4.2.24 on 2025-11-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
    ]
